name: posttest6_2009106051_ferry_fathurrahman
description: Buku resep digital praktis.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/cookfox.png"
  image_path_ios: "assets/icon/cookfox.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
    - assets/landing_page/
    - assets/recipe_image/
  
  fonts:
  - family: Quicksand
    fonts:
      - asset: fonts/Quicksand-Regular.ttf
      - asset: fonts/Quicksand-Light.ttf
        weight: 300
      - asset: fonts/Quicksand-Regular.ttf
        weight: 500
      - asset: fonts/Quicksand-SemiBold.ttf
        weight: 600
      - asset: fonts/Quicksand-Bold.ttf
        weight: 700
